import os
from Spoofers.JJJIIIJJJIIIIJJIIJJJIJJJJIIIIJJJJJJIIJI import JIJJJJJIIIIJJJIIJJIIJIIJJIIIJIJJIIIJJJIJIJJIIJJIIIIJIIII
from Spoofers.JJJJIJJJJIIIJJIIJIJJJIIJIIIJIIJIIJIJJIIJI import JIJJJJIIJJJJIIJIJJIIJJIIJJJJJJIIJJJII
from Spoofers.JJJJIJJJJIIIJJIIJIJJJIIJIIIJIIJIIJIJJIIJI import JIJJJJIIJJJJIIIIJJIIJJIIJJJJJJIIJJJII
from Spoofers.JJJJIJJJJIIIJJIIJIJJJIIJIIIJJJJJIIJI import JIJJJJJIIIIJJJIIJJIIJJIIJJIJIJIJIIJIIJJIJIJJIIIJIJJJIJ 
from Spoofers.JJJJIJJJJIIIJJIIJJJIJJJJIIJIJJJJJJIIJI import JIJJJJJIIIIJJJIIJJIIJJIIJJIJIJIJIIJIIJJIJ
from termcolor import colored 
os.system("color")
os.system("clear")
def JIJJJJJIIIIJJJIIJJIIJIIJJIIIJJIIJJJIIIIJIJIJJJIJ():
	JIJJJJJIIIIJJJIIJJIIJIIJJIIIJIJJIIIJJJIJ= int(input("0x69\> ")) 
	if JIJJJJJIIIIJJJIIJJIIJIIJJIIIJIJJIIIJJJIJ < 1:
		quit()
	elif JIJJJJJIIIIJJJIIJJIIJIIJJIIIJIJJIIIJJJIJ > 4:
	    JIJJJJJIIIIJJJIIJJIIJIIJJIIIJJIIJJJIIIIJIJIJJJIJ()
	elif JIJJJJJIIIIJJJIIJJIIJIIJJIIIJIJJIIIJJJIJ == 1:
		JIJJJJJIIIIJJJIIJJIIJIIJJIIIJIJJIIIJJJIJIJJIIJJIIIIJIIII()
	elif JIJJJJJIIIIJJJIIJJIIJIIJJIIIJIJJIIIJJJIJ == 2:
		JIJJJJIIJJJJIIIIJJIIJJIIJJJJJJIIJJJII()
	elif JIJJJJJIIIIJJJIIJJIIJIIJJIIIJIJJIIIJJJIJ == 3:
		JIJJJJJIIIIJJJIIJJIIJJIIJJIJIJIJIIJIIJJIJIJJIIIJIJJJIJ()
	elif JIJJJJJIIIIJJJIIJJIIJIIJJIIIJIJJIIIJJJIJ == 4:
		JIJJJJJIIIIJJJIIJJIIJJIIJJIJIJIJIIJIIJJIJ()

print(colored("""
 ██████╗ ██╗  ██╗ ██████╗ █████╗ 
██╔═████╗╚██╗██╔╝██╔════╝██╔══██╗
██║██╔██║ ╚███╔╝ ███████╗╚██████║
████╔╝██║ ██╔██╗ ██╔═══██╗╚═══██║
╚██████╔╝██╔╝ ██╗╚██████╔╝█████╔╝
 ╚═════╝ ╚═╝  ╚═╝ ╚═════╝ ╚════╝ 
                                 """, 'green'))
print(colored(" Created by 0xffvirus | Recoded by Leurak Hacker\n", 'green'))
print("""[1] Email Spoofer | [2] Fake Credit Card 
[3] Fake Address | [4] Fake Ip | [0] Exit \n""")

JIJJJJJIIIIJJJIIJJIIJIIJJIIIJJIIJJJIIIIJIJIJJJIJ()
