#Obfuscated by Leurak

JIIJJJJJJIIIJJIJIIJJJIIIJIIIJJJIIJJJIIJJJIIIIIJJJJJIIIIIJJJIJJJ = "visa"
JIIJJJJJJIIIJJIJIIJJJIIIJIIIJJJIIJJJIIJJJIIJIJJJJIIIIJIJJJIJJJ = "VISA"
JIIJJJJJIIIJIJJJJIIJJJIIIJIIIJJJJIJJJIIJIIJJJIJJJJJJIIIIJIIJIJJJ = "DISCOVER"
JIIJJJIJJIIIJJIJIIJJJIIIJIIIJJJIIJJJIIJJJIIJIJJJJIIIIJIJJJIJJJ = "MASTERCARD"
JIIJJJJJIIIJIJJIJIIJJJIIIJIIIJJJJIJJJIIJJJIIJJJJJJIIIIJIJJJIJJJ = "discover"
JIIJJJIJJIIIJJIJIIJJJIIIJIIIJJJIIJJJIIJJIJJIJIJJJJIIIIJIJJJIJJJ = "mastercard"
JIIJJJIJJIIIJJIJIIJJJIIIJIIIJJJIIJJJIIJJIJJIJIJJJJIJIJIIJIJJJIJJJ = "CC-CHECK: "
JIIJJJIJJIIIJJIJIIJIJIIIJIIIJIJIIIJJIIJJIJJIJIJJJJIJIJIIJIJJJIJJJ = "Credit Card:"
JIIJJJIJJIIIJJIJIIJIJIIIJIIIJIJIIIJJIIJJIJJIJIIJIJJIJIIJIIJIJJJIIIIJJJ = "CCV:"
JIIJJJIJJIIIJJIJIIJIJIIIJIIJJJJIIIJJIIJJIJJIJIJIJJIIJJIJIIJIJJJIIIIJJJ = "Expire Date:"
JIIJJJIJJIIIJJIJIIJIJIIIJIIJJJJIIIJJIIJJIJJIJIIIIIJIIIJJIJIIIIIIJJIIIIJJJ = "green"
JIIJJJIJJIIIJJIJIIJIJIIIIIJJIJJJIIIJJIIJJIJJIJIIIIIJIIJJJIJIIIIIIJJIIIIJJJ = "yellow"
JIIJJJIJJIIIJJIJIIJIJIIIIIJJIJJJIIIJJIIJJIJJJJJJJIJIIJIJJIJJIJIIJJJIIIIIJ = "red"
JIIJJJIJJIIIJJIJIIJIJIIIIIJJIJJJIIIJJIIJJIJJJJJJJIJIIJIJJJIJIIJJJIIIIIJ = "Over 10000+ Credit Cards .. Please try again"
JIIJJJJJIIIJJJIIJJJJJIIIJJJJIIIIIIIIIIJJJJIIIJJIIJJIIJJJIIIIJJIIJJJIIIJJII = "========================================"
JIIJJJJJIIIJJJIIJJJJJIIIJJJJIIIIIIJIIJIIJJJJIIIJJIIJJIIJJJIIIJJIIJJJIIIJJII = "Press Enter to exit ..."
JIIJJJIJJIIIJJIJIIJIJIIIIIJJIJJJIIIJJIIJJIJJJJJJJIIIJJIIJJJJJIIIIJIIIJJIIJJIIJ = "Count [0-10000]: "

def JIJJJJIIJJJJIIIIJJIIJJIIJJJJJJIIJJJII():
	print("[1] VISA | [2] MASTERCARD | [3] DISCOVER")
	JIJJJJIIJJJJIJJJIJIIIIJIIIJJJIJJIIJJJII = int(input("0x69\> ")) # User input option
	if JIJJJJIIJJJJIJJJIJIIIIJIIIJJJIJJIIJJJII < 1:
		JIJJJJIIJJJJIIIIJJIIJJIIJJJJJJIIJJJII()
	elif JIJJJJIIJJJJIJJJIJIIIIJIIIJJJIJJIIJJJII > 3:
		JIJJJJIIJJJJIIIIJJIIJJIIJJJJJJIIJJJII()
	elif JIJJJJIIJJJJIJJJIJIIIIJIIIJJJIJJIIJJJII == 1:
		JIJJJJIIJJJJIIJIJJIIJJIIJJJJJJIIJJJII(JIIJJJJJJIIIJJIJIIJJJIIIJIIIJJJIIJJJIIJJJIIIIIJJJJJIIIIIJJJIJJJ, JIIJJJJJJIIIJJIJIIJJJIIIJIIIJJJIIJJJIIJJJIIJIJJJJIIIIJIJJJIJJJ)
	elif JIJJJJIIJJJJIJJJIJIIIIJIIIJJJIJJIIJJJII == 2:
		JIJJJJIIJJJJIIJIJJIIJJIIJJJJJJIIJJJII(JIIJJJIJJIIIJJIJIIJJJIIIJIIIJJJIIJJJIIJJIJJIJIJJJJIIIIJIJJJIJJJ, JIIJJJIJJIIIJJIJIIJJJIIIJIIIJJJIIJJJIIJJJIIJIJJJJIIIIJIJJJIJJJ)
	elif JIJJJJIIJJJJIJJJIJIIIIJIIIJJJIJJIIJJJII == 3:
		JIJJJJIIJJJJIIJIJJIIJJIIJJJJJJIIJJJII(JIIJJJJJIIIJIJJIJIIJJJIIIJIIIJJJJIJJJIIJJJIIJJJJJJIIIIJIJJJIJJJ, JIIJJJJJIIIJIJJJJIIJJJIIIJIIIJJJJIJJJIIJIIJJJIJJJJJJIIIIJIIJIJJJ)

def JIJJJJIIJJJJIIJIJJIIJJIIIJJJJIJIIJJJII(JIJJJJIIJJJJIIJIJIIJJIIJJJJJJIIJJJII, JIJJJJIIJJJJIJJJIJIIJJIJJJJJJIIJJJII):
	import random
	from faker import Faker
	from termcolor import colored
	JIJIIJIJJIIJJJIIIIIJJJJJIIJIIIJJIIJJJII = ['1', '2', '3', '4', '5', '6', '7', '8', '9', '0']
	JIJIJJIIJJJIIJJJIIJJJIIIIIJJJIJJIIJJJII = "{}{}{}{} {}{}{}{} {}{}{}{} {}{}{}{}" 
	JIJJJJIIJJJJIJJJIJIIJIJJIIJJIIJJJII = Faker()
	JIJIIJIJJIJJJIIJJJIJJJJIIJJJIJJIIJJJII = int(input(JIIJJJIJJIIIJJIJIIJIJIIIIIJJIJJJIIIJJIIJJIJJJJJJJIIIJJIIJJJJJIIIIJIIIJJIIJJIIJ)) 
	if JIJIIJIJJIJJJIIJJJIJJJJIIJJJIJJIIJJJII <= 10000: 
		print(JIIJJJJJIIIJJJIIJJJJJIIIJJJJIIIIIIIIIIJJJJIIIJJIIJJIIJJJIIIIJJIIJJJIIIJJII)
		for i in range(JIJIIJIJJIJJJIIJJJIJJJJIIJJJIJJIIJJJII):
			JIJIIIIIJJJIIJJJIIIIIJIIIIJIIIJJIIJJJII = JIJJJJIIJJJJIJJJIJIIJIJJIIJJIIJJJII.credit_card_number(card_type=JIJJJJIIJJJJIIJIJIIJJIIJJJJJJIIJJJII)
			f = JIJIJJIIJJJIIJJJIIJJJIIIIIJJJIJJIIJJJII.format(*JIJIIIIIJJJIIJJJIIIIIJIIIIJIIIJJIIJJJII)
			JIJJJJIIJJJJIJJJIJIIIIJIIIJJIIJJIIJJJII = random.choice(JIJIIJIJJIIJJJIIIIIJJJJJIIJIIIJJIIJJJII) + random.choice(JIJIIJIJJIIJJJIIIIIJJJJJIIJIIIJJIIJJJII) + random.choice(JIJIIJIJJIIJJJIIIIIJJJJJIIJIIIJJIIJJJII)
			JIIJJJJJJIIIJJJJJIJIIIIIIJJJJIIIIIIJJJJ = JIJJJJIIJJJJIJJJIJIIJIJJIIJJIIJJJII.credit_card_expire(end='+6y')
			print(colored(JIIJJJIJJIIIJJIJIIJIJIIIJIIIJIJIIIJJIIJJIJJIJIJJJJIJIJIIJIJJJIJJJ, JIIJJJIJJIIIJJIJIIJIJIIIJIIJJJJIIIJJIIJJIJJIJIIIIIJIIIJJIJIIIIIIJJIIIIJJJ), f"{f} | " + JIJJJJIIJJJJIJJJIJIIJJIJJJJJJIIJJJII)
			print(colored(JIIJJJIJJIIIJJIJIIJIJIIIJIIIJIJIIIJJIIJJIJJIJIIJIJJIJIIJIIJIJJJIIIIJJJ, JIIJJJIJJIIIJJIJIIJIJIIIJIIJJJJIIIJJIIJJIJJIJIIIIIJIIIJJIJIIIIIIJJIIIIJJJ), JIJJJJIIJJJJIJJJIJIIIIJIIIJJIIJJIIJJJII)
			print(colored(JIIJJJIJJIIIJJIJIIJIJIIIJIIJJJJIIIJJIIJJIJJIJIJIJJIIJJIJIIJIJJJIIIIJJJ, JIIJJJIJJIIIJJIJIIJIJIIIJIIJJJJIIIJJIIJJIJJIJIIIIIJIIIJJIJIIIIIIJJIIIIJJJ), JIIJJJJJJIIIJJJJJIJIIIIIIJJJJIIIIIIJJJJ)
			JIIJJJJJJIIIJJJJJIJIIIIIIJJJJIIIIIIJJJJ = JIIJJJJJJIIIJJJJJIJIIIIIIJJJJIIIIIIJJJJ.replace("","")
			JIIJJJJJJIIIJIIIIIJJJJIIIJJIJJIIJJJJIIIIIIJJJJ = JIIJJJJJJIIIJJJJJIJIIIIIIJJJJIIIIIIJJJJ.replace("/", "|20")
			JIIJIIIIJIJJJIIIJIIIIJJIJIJJJJIIIJIJJJJ = f.replace(" ", "")
			print(colored(JIIJJJIJJIIIJJIJIIJJJIIIJIIIJJJIIJJJIIJJIJJIJIJJJJIJIJIIJIJJJIJJJ, JIIJJJIJJIIIJJIJIIJIJIIIIIJJIJJJIIIJJIIJJIJJIJIIIIIJIIJJJIJIIIIIIJJIIIIJJJ), JIIJIIIIJIJJJIIIJIIIIJJIJIJJJJIIIJIJJJJ + "|" + JIIJJJJJJIIIJIIIIIJJJJIIIJJIJJIIJJJJIIIIIIJJJJ + "|" + JIJJJJIIJJJJIJJJIJIIIIJIIIJJIIJJIIJJJII)
			print(JIIJJJJJIIIJJJIIJJJJJIIIJJJJIIIIIIIIIIJJJJIIIJJIIJJIIJJJIIIIJJIIJJJIIIJJII)
	else:
		print(JIIJJJIJJIIIJJIJIIJIJIIIIIJJIJJJIIIJJIIJJIJJJJJJJIJIIJIJJJIJIIJJJIIIIIJ) 
	input(colored(JIIJJJJJIIIJJJIIJJJJJIIIJJJJIIIIIIJIIJIIJJJJIIIJJIIJJIIJJJIIIJJIIJJJIIIJJII, JIIJJJIJJIIIJJIJIIJIJIIIIIJJIJJJIIIJJIIJJIJJJJJJJIJIIJIJJIJJIJIIJJJIIIIIJ))
	
def JIJJJJIIJJJJIIJIJJIIJJIIJJJJJIJIJIIIJIJJJII(JIJJJJIIJJJJIIJIJIIJJIIJJJJJJIIJJJII, JIJJJJIIJJJJIJJJIJIIJJIJJJJJJIIJJJII):
	import random
	from faker import Faker
	from termcolor import colored
	JIJIIJIJJIIJJJIIIIIJJJJJIIJIIIJJIIJJJII = ['1', '2', '3', '4', '5', '6', '7', '8', '9', '0']
	JIJIJJIIJJJIIJJJIIJJJIIIIIJJJIJJIIJJJII = "{}{}{}{} {}{}{}{} {}{}{}{} {}{}{}{}" 
	JIJJJJIIJJJJIJJJIJIIJIJJIIJJIIJJJII = Faker()
	JIJIIJIJJIJJJIIJJJIJJJJIIJJJIJJIIJJJII = int(input(JIIJJJIJJIIIJJIJIIJIJIIIIIJJIJJJIIIJJIIJJIJJJJJJJIIIJJIIJJJJJIIIIJIIIJJIIJJIIJ)) 
	if JIJIIJIJJIJJJIIJJJIJJJJIIJJJIJJIIJJJII <= 10000: 
		print(JIIJJJJJIIIJJJIIJJJJJIIIJJJJIIIIIIIIIIJJJJIIIJJIIJJIIJJJIIIIJJIIJJJIIIJJII)
		for i in range(JIJIIJIJJIJJJIIJJJIJJJJIIJJJIJJIIJJJII):
			JIJIIIIIJJJIIJJJIIIIIJIIIIJIIIJJIIJJJII = JIJJJJIIJJJJIJJJIJIIJIJJIIJJIIJJJII.credit_card_number(card_type=JIJJJJIIJJJJIIJIJIIJJIIJJJJJJIIJJJII)
			f = JIJIJJIIJJJIIJJJIIJJJIIIIIJJJIJJIIJJJII.format(*JIJIIIIIJJJIIJJJIIIIIJIIIIJIIIJJIIJJJII)
			JIJJJJIIJJJJIJJJIJIIIIJIIIJJIIJJIIJJJII = random.choice(JIJIIJIJJIIJJJIIIIIJJJJJIIJIIIJJIIJJJII) + random.choice(JIJIIJIJJIIJJJIIIIIJJJJJIIJIIIJJIIJJJII) + random.choice(JIJIIJIJJIIJJJIIIIIJJJJJIIJIIIJJIIJJJII)
			JIIJJJJJJIIIJJJJJIJIIIIIIJJJJIIIIIIJJJJ = JIJJJJIIJJJJIJJJIJIIJIJJIIJJIIJJJII.credit_card_expire(end='+6y')
			print(colored(JIIJJJIJJIIIJJIJIIJIJIIIJIIIJIJIIIJJIIJJIJJIJIJJJJIJIJIIJIJJJIJJJ, JIIJJJIJJIIIJJIJIIJIJIIIJIIJJJJIIIJJIIJJIJJIJIIIIIJIIIJJIJIIIIIIJJIIIIJJJ), f"{f} | " + JIJJJJIIJJJJIJJJIJIIJJIJJJJJJIIJJJII)
			print(colored(JIIJJJIJJIIIJJIJIIJIJIIIJIIIJIJIIIJJIIJJIJJIJIIJIJJIJIIJIIJIJJJIIIIJJJ, JIIJJJIJJIIIJJIJIIJIJIIIJIIJJJJIIIJJIIJJIJJIJIIIIIJIIIJJIJIIIIIIJJIIIIJJJ), JIJJJJIIJJJJIJJJIJIIIIJIIIJJIIJJIIJJJII)
			print(colored(JIIJJJIJJIIIJJIJIIJIJIIIJIIJJJJIIIJJIIJJIJJIJIJIJJIIJJIJIIJIJJJIIIIJJJ, JIIJJJIJJIIIJJIJIIJIJIIIJIIJJJJIIIJJIIJJIJJIJIIIIIJIIIJJIJIIIIIIJJIIIIJJJ), JIIJJJJJJIIIJJJJJIJIIIIIIJJJJIIIIIIJJJJ)
			JIIJJJJJJIIIJJJJJIJIIIIIIJJJJIIIIIIJJJJ = JIIJJJJJJIIIJJJJJIJIIIIIIJJJJIIIIIIJJJJ.replace("","")
			JIIJJJJJJIIIJIIIIIJJJJIIIJJIJJIIJJJJIIIIIIJJJJ = JIIJJJJJJIIIJJJJJIJIIIIIIJJJJIIIIIIJJJJ.replace("/", "|20")
			JIIJIIIIJIJJJIIIJIIIIJJIJIJJJJIIIJIJJJJ = f.replace(" ", "")
			print(colored(JIIJJJIJJIIIJJIJIIJJJIIIJIIIJJJIIJJJIIJJIJJIJIJJJJIJIJIIJIJJJIJJJ, JIIJJJIJJIIIJJIJIIJIJIIIIIJJIJJJIIIJJIIJJIJJIJIIIIIJIIJJJIJIIIIIIJJIIIIJJJ), JIIJIIIIJIJJJIIIJIIIIJJIJIJJJJIIIJIJJJJ + "|" + JIIJJJJJJIIIJIIIIIJJJJIIIJJIJJIIJJJJIIIIIIJJJJ + "|" + JIJJJJIIJJJJIJJJIJIIIIJIIIJJIIJJIIJJJII)
			print(JIIJJJJJIIIJJJIIJJJJJIIIJJJJIIIIIIIIIIJJJJIIIJJIIJJIIJJJIIIIJJIIJJJIIIJJII)
	else:
		print(JIIJJJIJJIIIJJIJIIJIJIIIIIJJIJJJIIIJJIIJJIJJJJJJJIJIIJIJJJIJIIJJJIIIIIJ) 
	input(colored(JIIJJJJJIIIJJJIIJJJJJIIIJJJJIIIIIIJIIJIIJJJJIIIJJIIJJIIJJJIIIJJIIJJJIIIJJII, JIIJJJIJJIIIJJIJIIJIJIIIIIJJIJJJIIIJJIIJJIJJJJJJJIJIIJIJJIJJIJIIJJJIIIIIJ))

def JIJJJJIIJJJJIIJIJJIIJJIJJJJJJJIIJJJII(JIJJJJIIJJJJIIJIJIIJJIIJJJJJJIIJJJII, JIJJJJIIJJJJIJJJIJIIJJIJJJJJJIIJJJII):
	import random
	from faker import Faker
	from termcolor import colored
	JIJIIJIJJIIJJJIIIIIJJJJJIIJIIIJJIIJJJII = ['1', '2', '3', '4', '5', '6', '7', '8', '9', '0']
	JIJIJJIIJJJIIJJJIIJJJIIIIIJJJIJJIIJJJII = "{}{}{}{} {}{}{}{} {}{}{}{} {}{}{}{}" 
	JIJJJJIIJJJJIJJJIJIIJIJJIIJJIIJJJII = Faker()
	JIJIIJIJJIJJJIIJJJIJJJJIIJJJIJJIIJJJII = int(input(JIIJJJIJJIIIJJIJIIJIJIIIIIJJIJJJIIIJJIIJJIJJJJJJJIIIJJIIJJJJJIIIIJIIIJJIIJJIIJ)) 
	if JIJIIJIJJIJJJIIJJJIJJJJIIJJJIJJIIJJJII <= 10000: 
		print(JIIJJJJJIIIJJJIIJJJJJIIIJJJJIIIIIIIIIIJJJJIIIJJIIJJIIJJJIIIIJJIIJJJIIIJJII)
		for i in range(JIJIIJIJJIJJJIIJJJIJJJJIIJJJIJJIIJJJII):
			JIJIIIIIJJJIIJJJIIIIIJIIIIJIIIJJIIJJJII = JIJJJJIIJJJJIJJJIJIIJIJJIIJJIIJJJII.credit_card_number(card_type=JIJJJJIIJJJJIIJIJIIJJIIJJJJJJIIJJJII)
			f = JIJIJJIIJJJIIJJJIIJJJIIIIIJJJIJJIIJJJII.format(*JIJIIIIIJJJIIJJJIIIIIJIIIIJIIIJJIIJJJII)
			JIJJJJIIJJJJIJJJIJIIIIJIIIJJIIJJIIJJJII = random.choice(JIJIIJIJJIIJJJIIIIIJJJJJIIJIIIJJIIJJJII) + random.choice(JIJIIJIJJIIJJJIIIIIJJJJJIIJIIIJJIIJJJII) + random.choice(JIJIIJIJJIIJJJIIIIIJJJJJIIJIIIJJIIJJJII)
			JIIJJJJJJIIIJJJJJIJIIIIIIJJJJIIIIIIJJJJ = JIJJJJIIJJJJIJJJIJIIJIJJIIJJIIJJJII.credit_card_expire(end='+6y')
			print(colored(JIIJJJIJJIIIJJIJIIJIJIIIJIIIJIJIIIJJIIJJIJJIJIJJJJIJIJIIJIJJJIJJJ, JIIJJJIJJIIIJJIJIIJIJIIIJIIJJJJIIIJJIIJJIJJIJIIIIIJIIIJJIJIIIIIIJJIIIIJJJ), f"{f} | " + JIJJJJIIJJJJIJJJIJIIJJIJJJJJJIIJJJII)
			print(colored(JIIJJJIJJIIIJJIJIIJIJIIIJIIIJIJIIIJJIIJJIJJIJIIJIJJIJIIJIIJIJJJIIIIJJJ, JIIJJJIJJIIIJJIJIIJIJIIIJIIJJJJIIIJJIIJJIJJIJIIIIIJIIIJJIJIIIIIIJJIIIIJJJ), JIJJJJIIJJJJIJJJIJIIIIJIIIJJIIJJIIJJJII)
			print(colored(JIIJJJIJJIIIJJIJIIJIJIIIJIIJJJJIIIJJIIJJIJJIJIJIJJIIJJIJIIJIJJJIIIIJJJ, JIIJJJIJJIIIJJIJIIJIJIIIJIIJJJJIIIJJIIJJIJJIJIIIIIJIIIJJIJIIIIIIJJIIIIJJJ), JIIJJJJJJIIIJJJJJIJIIIIIIJJJJIIIIIIJJJJ)
			JIIJJJJJJIIIJJJJJIJIIIIIIJJJJIIIIIIJJJJ = JIIJJJJJJIIIJJJJJIJIIIIIIJJJJIIIIIIJJJJ.replace("","")
			JIIJJJJJJIIIJIIIIIJJJJIIIJJIJJIIJJJJIIIIIIJJJJ = JIIJJJJJJIIIJJJJJIJIIIIIIJJJJIIIIIIJJJJ.replace("/", "|20")
			JIIJIIIIJIJJJIIIJIIIIJJIJIJJJJIIIJIJJJJ = f.replace(" ", "")
			print(colored(JIIJJJIJJIIIJJIJIIJJJIIIJIIIJJJIIJJJIIJJIJJIJIJJJJIJIJIIJIJJJIJJJ, JIIJJJIJJIIIJJIJIIJIJIIIIIJJIJJJIIIJJIIJJIJJIJIIIIIJIIJJJIJIIIIIIJJIIIIJJJ), JIIJIIIIJIJJJIIIJIIIIJJIJIJJJJIIIJIJJJJ + "|" + JIIJJJJJJIIIJIIIIIJJJJIIIJJIJJIIJJJJIIIIIIJJJJ + "|" + JIJJJJIIJJJJIJJJIJIIIIJIIIJJIIJJIIJJJII)
			print(JIIJJJJJIIIJJJIIJJJJJIIIJJJJIIIIIIIIIIJJJJIIIJJIIJJIIJJJIIIIJJIIJJJIIIJJII)
	else:
		print(JIIJJJIJJIIIJJIJIIJIJIIIIIJJIJJJIIIJJIIJJIJJJJJJJIJIIJIJJJIJIIJJJIIIIIJ) 
	input(colored(JIIJJJJJIIIJJJIIJJJJJIIIJJJJIIIIIIJIIJIIJJJJIIIJJIIJJIIJJJIIIJJIIJJJIIIJJII, JIIJJJIJJIIIJJIJIIJIJIIIIIJJIJJJIIIJJIIJJIJJJJJJJIJIIJIJJIJJIJIIJJJIIIIIJ))
	
def JIJJJJIIJJJJIIJIJJIIJJIIJJJJJJIIJJJII(JIJJJJIIJJJJIIJIJIIJJIIJJJJJJIIJJJII, JIJJJJIIJJJJIJJJIJIIJJIJJJJJJIIJJJII):
	import random
	from faker import Faker
	from termcolor import colored
	JIJIIJIJJIIJJJIIIIIJJJJJIIJIIIJJIIJJJII = ['1', '2', '3', '4', '5', '6', '7', '8', '9', '0']
	JIJIJJIIJJJIIJJJIIJJJIIIIIJJJIJJIIJJJII = "{}{}{}{} {}{}{}{} {}{}{}{} {}{}{}{}" 
	JIJJJJIIJJJJIJJJIJIIJIJJIIJJIIJJJII = Faker()
	JIJIIJIJJIJJJIIJJJIJJJJIIJJJIJJIIJJJII = int(input(JIIJJJIJJIIIJJIJIIJIJIIIIIJJIJJJIIIJJIIJJIJJJJJJJIIIJJIIJJJJJIIIIJIIIJJIIJJIIJ)) 
	if JIJIIJIJJIJJJIIJJJIJJJJIIJJJIJJIIJJJII <= 10000: 
		print(JIIJJJJJIIIJJJIIJJJJJIIIJJJJIIIIIIIIIIJJJJIIIJJIIJJIIJJJIIIIJJIIJJJIIIJJII)
		for i in range(JIJIIJIJJIJJJIIJJJIJJJJIIJJJIJJIIJJJII):
			JIJIIIIIJJJIIJJJIIIIIJIIIIJIIIJJIIJJJII = JIJJJJIIJJJJIJJJIJIIJIJJIIJJIIJJJII.credit_card_number(card_type=JIJJJJIIJJJJIIJIJIIJJIIJJJJJJIIJJJII)
			f = JIJIJJIIJJJIIJJJIIJJJIIIIIJJJIJJIIJJJII.format(*JIJIIIIIJJJIIJJJIIIIIJIIIIJIIIJJIIJJJII)
			JIJJJJIIJJJJIJJJIJIIIIJIIIJJIIJJIIJJJII = random.choice(JIJIIJIJJIIJJJIIIIIJJJJJIIJIIIJJIIJJJII) + random.choice(JIJIIJIJJIIJJJIIIIIJJJJJIIJIIIJJIIJJJII) + random.choice(JIJIIJIJJIIJJJIIIIIJJJJJIIJIIIJJIIJJJII)
			JIIJJJJJJIIIJJJJJIJIIIIIIJJJJIIIIIIJJJJ = JIJJJJIIJJJJIJJJIJIIJIJJIIJJIIJJJII.credit_card_expire(end='+6y')
			print(colored(JIIJJJIJJIIIJJIJIIJIJIIIJIIIJIJIIIJJIIJJIJJIJIJJJJIJIJIIJIJJJIJJJ, JIIJJJIJJIIIJJIJIIJIJIIIJIIJJJJIIIJJIIJJIJJIJIIIIIJIIIJJIJIIIIIIJJIIIIJJJ), f"{f} | " + JIJJJJIIJJJJIJJJIJIIJJIJJJJJJIIJJJII)
			print(colored(JIIJJJIJJIIIJJIJIIJIJIIIJIIIJIJIIIJJIIJJIJJIJIIJIJJIJIIJIIJIJJJIIIIJJJ, JIIJJJIJJIIIJJIJIIJIJIIIJIIJJJJIIIJJIIJJIJJIJIIIIIJIIIJJIJIIIIIIJJIIIIJJJ), JIJJJJIIJJJJIJJJIJIIIIJIIIJJIIJJIIJJJII)
			print(colored(JIIJJJIJJIIIJJIJIIJIJIIIJIIJJJJIIIJJIIJJIJJIJIJIJJIIJJIJIIJIJJJIIIIJJJ, JIIJJJIJJIIIJJIJIIJIJIIIJIIJJJJIIIJJIIJJIJJIJIIIIIJIIIJJIJIIIIIIJJIIIIJJJ), JIIJJJJJJIIIJJJJJIJIIIIIIJJJJIIIIIIJJJJ)
			JIIJJJJJJIIIJJJJJIJIIIIIIJJJJIIIIIIJJJJ = JIIJJJJJJIIIJJJJJIJIIIIIIJJJJIIIIIIJJJJ.replace("","")
			JIIJJJJJJIIIJIIIIIJJJJIIIJJIJJIIJJJJIIIIIIJJJJ = JIIJJJJJJIIIJJJJJIJIIIIIIJJJJIIIIIIJJJJ.replace("/", "|20")
			JIIJIIIIJIJJJIIIJIIIIJJIJIJJJJIIIJIJJJJ = f.replace(" ", "")
			print(colored(JIIJJJIJJIIIJJIJIIJJJIIIJIIIJJJIIJJJIIJJIJJIJIJJJJIJIJIIJIJJJIJJJ, JIIJJJIJJIIIJJIJIIJIJIIIIIJJIJJJIIIJJIIJJIJJIJIIIIIJIIJJJIJIIIIIIJJIIIIJJJ), JIIJIIIIJIJJJIIIJIIIIJJIJIJJJJIIIJIJJJJ + "|" + JIIJJJJJJIIIJIIIIIJJJJIIIJJIJJIIJJJJIIIIIIJJJJ + "|" + JIJJJJIIJJJJIJJJIJIIIIJIIIJJIIJJIIJJJII)
			print(JIIJJJJJIIIJJJIIJJJJJIIIJJJJIIIIIIIIIIJJJJIIIJJIIJJIIJJJIIIIJJIIJJJIIIJJII)
	else:
		print(JIIJJJIJJIIIJJIJIIJIJIIIIIJJIJJJIIIJJIIJJIJJJJJJJIJIIJIJJJIJIIJJJIIIIIJ) 
	input(colored(JIIJJJJJIIIJJJIIJJJJJIIIJJJJIIIIIIJIIJIIJJJJIIIJJIIJJIIJJJIIIJJIIJJJIIIJJII, JIIJJJIJJIIIJJIJIIJIJIIIIIJJIJJJIIIJJIIJJIJJJJJJJIJIIJIJJIJJIJIIJJJIIIIIJ))
	
def JIJJJJIIJJJIIJIJJIIJJIIJJJJJJIIJJJII(JIJJJJIIJJJJIIJIJIIJJIIJJJJJJIIJJJII, JIJJJJIIJJJJIJJJIJIIJJIJJJJJJIIJJJII):
	import random
	from faker import Faker
	from termcolor import colored
	JIJIIJIJJIIJJJIIIIIJJJJJIIJIIIJJIIJJJII = ['1', '2', '3', '4', '5', '6', '7', '8', '9', '0']
	JIJIJJIIJJJIIJJJIIJJJIIIIIJJJIJJIIJJJII = "{}{}{}{} {}{}{}{} {}{}{}{} {}{}{}{}" 
	JIJJJJIIJJJJIJJJIJIIJIJJIIJJIIJJJII = Faker()
	JIJIIJIJJIJJJIIJJJIJJJJIIJJJIJJIIJJJII = int(input(JIIJJJIJJIIIJJIJIIJIJIIIIIJJIJJJIIIJJIIJJIJJJJJJJIIIJJIIJJJJJIIIIJIIIJJIIJJIIJ)) 
	if JIJIIJIJJIJJJIIJJJIJJJJIIJJJIJJIIJJJII <= 10000: 
		print(JIIJJJJJIIIJJJIIJJJJJIIIJJJJIIIIIIIIIIJJJJIIIJJIIJJIIJJJIIIIJJIIJJJIIIJJII)
		for i in range(JIJIIJIJJIJJJIIJJJIJJJJIIJJJIJJIIJJJII):
			JIJIIIIIJJJIIJJJIIIIIJIIIIJIIIJJIIJJJII = JIJJJJIIJJJJIJJJIJIIJIJJIIJJIIJJJII.credit_card_number(card_type=JIJJJJIIJJJJIIJIJIIJJIIJJJJJJIIJJJII)
			f = JIJIJJIIJJJIIJJJIIJJJIIIIIJJJIJJIIJJJII.format(*JIJIIIIIJJJIIJJJIIIIIJIIIIJIIIJJIIJJJII)
			JIJJJJIIJJJJIJJJIJIIIIJIIIJJIIJJIIJJJII = random.choice(JIJIIJIJJIIJJJIIIIIJJJJJIIJIIIJJIIJJJII) + random.choice(JIJIIJIJJIIJJJIIIIIJJJJJIIJIIIJJIIJJJII) + random.choice(JIJIIJIJJIIJJJIIIIIJJJJJIIJIIIJJIIJJJII)
			JIIJJJJJJIIIJJJJJIJIIIIIIJJJJIIIIIIJJJJ = JIJJJJIIJJJJIJJJIJIIJIJJIIJJIIJJJII.credit_card_expire(end='+6y')
			print(colored(JIIJJJIJJIIIJJIJIIJIJIIIJIIIJIJIIIJJIIJJIJJIJIJJJJIJIJIIJIJJJIJJJ, JIIJJJIJJIIIJJIJIIJIJIIIJIIJJJJIIIJJIIJJIJJIJIIIIIJIIIJJIJIIIIIIJJIIIIJJJ), f"{f} | " + JIJJJJIIJJJJIJJJIJIIJJIJJJJJJIIJJJII)
			print(colored(JIIJJJIJJIIIJJIJIIJIJIIIJIIIJIJIIIJJIIJJIJJIJIIJIJJIJIIJIIJIJJJIIIIJJJ, JIIJJJIJJIIIJJIJIIJIJIIIJIIJJJJIIIJJIIJJIJJIJIIIIIJIIIJJIJIIIIIIJJIIIIJJJ), JIJJJJIIJJJJIJJJIJIIIIJIIIJJIIJJIIJJJII)
			print(colored(JIIJJJIJJIIIJJIJIIJIJIIIJIIJJJJIIIJJIIJJIJJIJIJIJJIIJJIJIIJIJJJIIIIJJJ, JIIJJJIJJIIIJJIJIIJIJIIIJIIJJJJIIIJJIIJJIJJIJIIIIIJIIIJJIJIIIIIIJJIIIIJJJ), JIIJJJJJJIIIJJJJJIJIIIIIIJJJJIIIIIIJJJJ)
			JIIJJJJJJIIIJJJJJIJIIIIIIJJJJIIIIIIJJJJ = JIIJJJJJJIIIJJJJJIJIIIIIIJJJJIIIIIIJJJJ.replace("","")
			JIIJJJJJJIIIJIIIIIJJJJIIIJJIJJIIJJJJIIIIIIJJJJ = JIIJJJJJJIIIJJJJJIJIIIIIIJJJJIIIIIIJJJJ.replace("/", "|20")
			JIIJIIIIJIJJJIIIJIIIIJJIJIJJJJIIIJIJJJJ = f.replace(" ", "")
			print(colored(JIIJJJIJJIIIJJIJIIJJJIIIJIIIJJJIIJJJIIJJIJJIJIJJJJIJIJIIJIJJJIJJJ, JIIJJJIJJIIIJJIJIIJIJIIIIIJJIJJJIIIJJIIJJIJJIJIIIIIJIIJJJIJIIIIIIJJIIIIJJJ), JIIJIIIIJIJJJIIIJIIIIJJIJIJJJJIIIJIJJJJ + "|" + JIIJJJJJJIIIJIIIIIJJJJIIIJJIJJIIJJJJIIIIIIJJJJ + "|" + JIJJJJIIJJJJIJJJIJIIIIJIIIJJIIJJIIJJJII)
			print(JIIJJJJJIIIJJJIIJJJJJIIIJJJJIIIIIIIIIIJJJJIIIJJIIJJIIJJJIIIIJJIIJJJIIIJJII)
	else:
		print(JIIJJJIJJIIIJJIJIIJIJIIIIIJJIJJJIIIJJIIJJIJJJJJJJIJIIJIJJJIJIIJJJIIIIIJ) 
	input(colored(JIIJJJJJIIIJJJIIJJJJJIIIJJJJIIIIIIJIIJIIJJJJIIIJJIIJJIIJJJIIIJJIIJJJIIIJJII, JIIJJJIJJIIIJJIJIIJIJIIIIIJJIJJJIIIJJIIJJIJJJJJJJIJIIJIJJIJJIJIIJJJIIIIIJ))
	
def JIJJJJIIJJJJIIJIJJIIJJIIJJJIJIIJJJII(JIJJJJIIJJJJIIJIJIIJJIIJJJJJJIIJJJII, JIJJJJIIJJJJIJJJIJIIJJIJJJJJJIIJJJII):
	import random
	from faker import Faker
	from termcolor import colored
	JIJIIJIJJIIJJJIIIIIJJJJJIIJIIIJJIIJJJII = ['1', '2', '3', '4', '5', '6', '7', '8', '9', '0']
	JIJIJJIIJJJIIJJJIIJJJIIIIIJJJIJJIIJJJII = "{}{}{}{} {}{}{}{} {}{}{}{} {}{}{}{}" 
	JIJJJJIIJJJJIJJJIJIIJIJJIIJJIIJJJII = Faker()
	JIJIIJIJJIJJJIIJJJIJJJJIIJJJIJJIIJJJII = int(input(JIIJJJIJJIIIJJIJIIJIJIIIIIJJIJJJIIIJJIIJJIJJJJJJJIIIJJIIJJJJJIIIIJIIIJJIIJJIIJ)) 
	if JIJIIJIJJIJJJIIJJJIJJJJIIJJJIJJIIJJJII <= 10000: 
		print(JIIJJJJJIIIJJJIIJJJJJIIIJJJJIIIIIIIIIIJJJJIIIJJIIJJIIJJJIIIIJJIIJJJIIIJJII)
		for i in range(JIJIIJIJJIJJJIIJJJIJJJJIIJJJIJJIIJJJII):
			JIJIIIIIJJJIIJJJIIIIIJIIIIJIIIJJIIJJJII = JIJJJJIIJJJJIJJJIJIIJIJJIIJJIIJJJII.credit_card_number(card_type=JIJJJJIIJJJJIIJIJIIJJIIJJJJJJIIJJJII)
			f = JIJIJJIIJJJIIJJJIIJJJIIIIIJJJIJJIIJJJII.format(*JIJIIIIIJJJIIJJJIIIIIJIIIIJIIIJJIIJJJII)
			JIJJJJIIJJJJIJJJIJIIIIJIIIJJIIJJIIJJJII = random.choice(JIJIIJIJJIIJJJIIIIIJJJJJIIJIIIJJIIJJJII) + random.choice(JIJIIJIJJIIJJJIIIIIJJJJJIIJIIIJJIIJJJII) + random.choice(JIJIIJIJJIIJJJIIIIIJJJJJIIJIIIJJIIJJJII)
			JIIJJJJJJIIIJJJJJIJIIIIIIJJJJIIIIIIJJJJ = JIJJJJIIJJJJIJJJIJIIJIJJIIJJIIJJJII.credit_card_expire(end='+6y')
			print(colored(JIIJJJIJJIIIJJIJIIJIJIIIJIIIJIJIIIJJIIJJIJJIJIJJJJIJIJIIJIJJJIJJJ, JIIJJJIJJIIIJJIJIIJIJIIIJIIJJJJIIIJJIIJJIJJIJIIIIIJIIIJJIJIIIIIIJJIIIIJJJ), f"{f} | " + JIJJJJIIJJJJIJJJIJIIJJIJJJJJJIIJJJII)
			print(colored(JIIJJJIJJIIIJJIJIIJIJIIIJIIIJIJIIIJJIIJJIJJIJIIJIJJIJIIJIIJIJJJIIIIJJJ, JIIJJJIJJIIIJJIJIIJIJIIIJIIJJJJIIIJJIIJJIJJIJIIIIIJIIIJJIJIIIIIIJJIIIIJJJ), JIJJJJIIJJJJIJJJIJIIIIJIIIJJIIJJIIJJJII)
			print(colored(JIIJJJIJJIIIJJIJIIJIJIIIJIIJJJJIIIJJIIJJIJJIJIJIJJIIJJIJIIJIJJJIIIIJJJ, JIIJJJIJJIIIJJIJIIJIJIIIJIIJJJJIIIJJIIJJIJJIJIIIIIJIIIJJIJIIIIIIJJIIIIJJJ), JIIJJJJJJIIIJJJJJIJIIIIIIJJJJIIIIIIJJJJ)
			JIIJJJJJJIIIJJJJJIJIIIIIIJJJJIIIIIIJJJJ = JIIJJJJJJIIIJJJJJIJIIIIIIJJJJIIIIIIJJJJ.replace("","")
			JIIJJJJJJIIIJIIIIIJJJJIIIJJIJJIIJJJJIIIIIIJJJJ = JIIJJJJJJIIIJJJJJIJIIIIIIJJJJIIIIIIJJJJ.replace("/", "|20")
			JIIJIIIIJIJJJIIIJIIIIJJIJIJJJJIIIJIJJJJ = f.replace(" ", "")
			print(colored(JIIJJJIJJIIIJJIJIIJJJIIIJIIIJJJIIJJJIIJJIJJIJIJJJJIJIJIIJIJJJIJJJ, JIIJJJIJJIIIJJIJIIJIJIIIIIJJIJJJIIIJJIIJJIJJIJIIIIIJIIJJJIJIIIIIIJJIIIIJJJ), JIIJIIIIJIJJJIIIJIIIIJJIJIJJJJIIIJIJJJJ + "|" + JIIJJJJJJIIIJIIIIIJJJJIIIJJIJJIIJJJJIIIIIIJJJJ + "|" + JIJJJJIIJJJJIJJJIJIIIIJIIIJJIIJJIIJJJII)
			print(JIIJJJJJIIIJJJIIJJJJJIIIJJJJIIIIIIIIIIJJJJIIIJJIIJJIIJJJIIIIJJIIJJJIIIJJII)
	else:
		print(JIIJJJIJJIIIJJIJIIJIJIIIIIJJIJJJIIIJJIIJJIJJJJJJJIJIIJIJJJIJIIJJJIIIIIJ) 
	input(colored(JIIJJJJJIIIJJJIIJJJJJIIIJJJJIIIIIIJIIJIIJJJJIIIJJIIJJIIJJJIIIJJIIJJJIIIJJII, JIIJJJIJJIIIJJIJIIJIJIIIIIJJIJJJIIIJJIIJJIJJJJJJJIJIIJIJJIJJIJIIJJJIIIIIJ))
	
def JIJJJJIIJJJJIIJIJIIJJIIIIJJJJJIIJJJII(JIJJJJIIJJJJIIJIJIIJJIIJJJJJJIIJJJII, JIJJJJIIJJJJIJJJIJIIJJIJJJJJJIIJJJII):
	import random
	from faker import Faker
	from termcolor import colored
	JIJIIJIJJIIJJJIIIIIJJJJJIIJIIIJJIIJJJII = ['1', '2', '3', '4', '5', '6', '7', '8', '9', '0']
	JIJIJJIIJJJIIJJJIIJJJIIIIIJJJIJJIIJJJII = "{}{}{}{} {}{}{}{} {}{}{}{} {}{}{}{}" 
	JIJJJJIIJJJJIJJJIJIIJIJJIIJJIIJJJII = Faker()
	JIJIIJIJJIJJJIIJJJIJJJJIIJJJIJJIIJJJII = int(input(JIIJJJIJJIIIJJIJIIJIJIIIIIJJIJJJIIIJJIIJJIJJJJJJJIIIJJIIJJJJJIIIIJIIIJJIIJJIIJ)) 
	if JIJIIJIJJIJJJIIJJJIJJJJIIJJJIJJIIJJJII <= 10000: 
		print(JIIJJJJJIIIJJJIIJJJJJIIIJJJJIIIIIIIIIIJJJJIIIJJIIJJIIJJJIIIIJJIIJJJIIIJJII)
		for i in range(JIJIIJIJJIJJJIIJJJIJJJJIIJJJIJJIIJJJII):
			JIJIIIIIJJJIIJJJIIIIIJIIIIJIIIJJIIJJJII = JIJJJJIIJJJJIJJJIJIIJIJJIIJJIIJJJII.credit_card_number(card_type=JIJJJJIIJJJJIIJIJIIJJIIJJJJJJIIJJJII)
			f = JIJIJJIIJJJIIJJJIIJJJIIIIIJJJIJJIIJJJII.format(*JIJIIIIIJJJIIJJJIIIIIJIIIIJIIIJJIIJJJII)
			JIJJJJIIJJJJIJJJIJIIIIJIIIJJIIJJIIJJJII = random.choice(JIJIIJIJJIIJJJIIIIIJJJJJIIJIIIJJIIJJJII) + random.choice(JIJIIJIJJIIJJJIIIIIJJJJJIIJIIIJJIIJJJII) + random.choice(JIJIIJIJJIIJJJIIIIIJJJJJIIJIIIJJIIJJJII)
			JIIJJJJJJIIIJJJJJIJIIIIIIJJJJIIIIIIJJJJ = JIJJJJIIJJJJIJJJIJIIJIJJIIJJIIJJJII.credit_card_expire(end='+6y')
			print(colored(JIIJJJIJJIIIJJIJIIJIJIIIJIIIJIJIIIJJIIJJIJJIJIJJJJIJIJIIJIJJJIJJJ, JIIJJJIJJIIIJJIJIIJIJIIIJIIJJJJIIIJJIIJJIJJIJIIIIIJIIIJJIJIIIIIIJJIIIIJJJ), f"{f} | " + JIJJJJIIJJJJIJJJIJIIJJIJJJJJJIIJJJII)
			print(colored(JIIJJJIJJIIIJJIJIIJIJIIIJIIIJIJIIIJJIIJJIJJIJIIJIJJIJIIJIIJIJJJIIIIJJJ, JIIJJJIJJIIIJJIJIIJIJIIIJIIJJJJIIIJJIIJJIJJIJIIIIIJIIIJJIJIIIIIIJJIIIIJJJ), JIJJJJIIJJJJIJJJIJIIIIJIIIJJIIJJIIJJJII)
			print(colored(JIIJJJIJJIIIJJIJIIJIJIIIJIIJJJJIIIJJIIJJIJJIJIJIJJIIJJIJIIJIJJJIIIIJJJ, JIIJJJIJJIIIJJIJIIJIJIIIJIIJJJJIIIJJIIJJIJJIJIIIIIJIIIJJIJIIIIIIJJIIIIJJJ), JIIJJJJJJIIIJJJJJIJIIIIIIJJJJIIIIIIJJJJ)
			JIIJJJJJJIIIJJJJJIJIIIIIIJJJJIIIIIIJJJJ = JIIJJJJJJIIIJJJJJIJIIIIIIJJJJIIIIIIJJJJ.replace("","")
			JIIJJJJJJIIIJIIIIIJJJJIIIJJIJJIIJJJJIIIIIIJJJJ = JIIJJJJJJIIIJJJJJIJIIIIIIJJJJIIIIIIJJJJ.replace("/", "|20")
			JIIJIIIIJIJJJIIIJIIIIJJIJIJJJJIIIJIJJJJ = f.replace(" ", "")
			print(colored(JIIJJJIJJIIIJJIJIIJJJIIIJIIIJJJIIJJJIIJJIJJIJIJJJJIJIJIIJIJJJIJJJ, JIIJJJIJJIIIJJIJIIJIJIIIIIJJIJJJIIIJJIIJJIJJIJIIIIIJIIJJJIJIIIIIIJJIIIIJJJ), JIIJIIIIJIJJJIIIJIIIIJJIJIJJJJIIIJIJJJJ + "|" + JIIJJJJJJIIIJIIIIIJJJJIIIJJIJJIIJJJJIIIIIIJJJJ + "|" + JIJJJJIIJJJJIJJJIJIIIIJIIIJJIIJJIIJJJII)
			print(JIIJJJJJIIIJJJIIJJJJJIIIJJJJIIIIIIIIIIJJJJIIIJJIIJJIIJJJIIIIJJIIJJJIIIJJII)
	else:
		print(JIIJJJIJJIIIJJIJIIJIJIIIIIJJIJJJIIIJJIIJJIJJJJJJJIJIIJIJJJIJIIJJJIIIIIJ) 
	input(colored(JIIJJJJJIIIJJJIIJJJJJIIIJJJJIIIIIIJIIJIIJJJJIIIJJIIJJIIJJJIIIJJIIJJJIIIJJII, JIIJJJIJJIIIJJIJIIJIJIIIIIJJIJJJIIIJJIIJJIJJJJJJJIJIIJIJJIJJIJIIJJJIIIIIJ))
	
def JIJJJJIIJJJJIIJIJJIIJJIIIJJIJIJJIIJJJII(JIJJJJIIJJJJIIJIJIIJJIIJJJJJJIIJJJII, JIJJJJIIJJJJIJJJIJIIJJIJJJJJJIIJJJII):
	import random
	from faker import Faker
	from termcolor import colored
	JIJIIJIJJIIJJJIIIIIJJJJJIIJIIIJJIIJJJII = ['1', '2', '3', '4', '5', '6', '7', '8', '9', '0']
	JIJIJJIIJJJIIJJJIIJJJIIIIIJJJIJJIIJJJII = "{}{}{}{} {}{}{}{} {}{}{}{} {}{}{}{}" 
	JIJJJJIIJJJJIJJJIJIIJIJJIIJJIIJJJII = Faker()
	JIJIIJIJJIJJJIIJJJIJJJJIIJJJIJJIIJJJII = int(input(JIIJJJIJJIIIJJIJIIJIJIIIIIJJIJJJIIIJJIIJJIJJJJJJJIIIJJIIJJJJJIIIIJIIIJJIIJJIIJ)) 
	if JIJIIJIJJIJJJIIJJJIJJJJIIJJJIJJIIJJJII <= 10000: 
		print(JIIJJJJJIIIJJJIIJJJJJIIIJJJJIIIIIIIIIIJJJJIIIJJIIJJIIJJJIIIIJJIIJJJIIIJJII)
		for i in range(JIJIIJIJJIJJJIIJJJIJJJJIIJJJIJJIIJJJII):
			JIJIIIIIJJJIIJJJIIIIIJIIIIJIIIJJIIJJJII = JIJJJJIIJJJJIJJJIJIIJIJJIIJJIIJJJII.credit_card_number(card_type=JIJJJJIIJJJJIIJIJIIJJIIJJJJJJIIJJJII)
			f = JIJIJJIIJJJIIJJJIIJJJIIIIIJJJIJJIIJJJII.format(*JIJIIIIIJJJIIJJJIIIIIJIIIIJIIIJJIIJJJII)
			JIJJJJIIJJJJIJJJIJIIIIJIIIJJIIJJIIJJJII = random.choice(JIJIIJIJJIIJJJIIIIIJJJJJIIJIIIJJIIJJJII) + random.choice(JIJIIJIJJIIJJJIIIIIJJJJJIIJIIIJJIIJJJII) + random.choice(JIJIIJIJJIIJJJIIIIIJJJJJIIJIIIJJIIJJJII)
			JIIJJJJJJIIIJJJJJIJIIIIIIJJJJIIIIIIJJJJ = JIJJJJIIJJJJIJJJIJIIJIJJIIJJIIJJJII.credit_card_expire(end='+6y')
			print(colored(JIIJJJIJJIIIJJIJIIJIJIIIJIIIJIJIIIJJIIJJIJJIJIJJJJIJIJIIJIJJJIJJJ, JIIJJJIJJIIIJJIJIIJIJIIIJIIJJJJIIIJJIIJJIJJIJIIIIIJIIIJJIJIIIIIIJJIIIIJJJ), f"{f} | " + JIJJJJIIJJJJIJJJIJIIJJIJJJJJJIIJJJII)
			print(colored(JIIJJJIJJIIIJJIJIIJIJIIIJIIIJIJIIIJJIIJJIJJIJIIJIJJIJIIJIIJIJJJIIIIJJJ, JIIJJJIJJIIIJJIJIIJIJIIIJIIJJJJIIIJJIIJJIJJIJIIIIIJIIIJJIJIIIIIIJJIIIIJJJ), JIJJJJIIJJJJIJJJIJIIIIJIIIJJIIJJIIJJJII)
			print(colored(JIIJJJIJJIIIJJIJIIJIJIIIJIIJJJJIIIJJIIJJIJJIJIJIJJIIJJIJIIJIJJJIIIIJJJ, JIIJJJIJJIIIJJIJIIJIJIIIJIIJJJJIIIJJIIJJIJJIJIIIIIJIIIJJIJIIIIIIJJIIIIJJJ), JIIJJJJJJIIIJJJJJIJIIIIIIJJJJIIIIIIJJJJ)
			JIIJJJJJJIIIJJJJJIJIIIIIIJJJJIIIIIIJJJJ = JIIJJJJJJIIIJJJJJIJIIIIIIJJJJIIIIIIJJJJ.replace("","")
			JIIJJJJJJIIIJIIIIIJJJJIIIJJIJJIIJJJJIIIIIIJJJJ = JIIJJJJJJIIIJJJJJIJIIIIIIJJJJIIIIIIJJJJ.replace("/", "|20")
			JIIJIIIIJIJJJIIIJIIIIJJIJIJJJJIIIJIJJJJ = f.replace(" ", "")
			print(colored(JIIJJJIJJIIIJJIJIIJJJIIIJIIIJJJIIJJJIIJJIJJIJIJJJJIJIJIIJIJJJIJJJ, JIIJJJIJJIIIJJIJIIJIJIIIIIJJIJJJIIIJJIIJJIJJIJIIIIIJIIJJJIJIIIIIIJJIIIIJJJ), JIIJIIIIJIJJJIIIJIIIIJJIJIJJJJIIIJIJJJJ + "|" + JIIJJJJJJIIIJIIIIIJJJJIIIJJIJJIIJJJJIIIIIIJJJJ + "|" + JIJJJJIIJJJJIJJJIJIIIIJIIIJJIIJJIIJJJII)
			print(JIIJJJJJIIIJJJIIJJJJJIIIJJJJIIIIIIIIIIJJJJIIIJJIIJJIIJJJIIIIJJIIJJJIIIJJII)
	else:
		print(JIIJJJIJJIIIJJIJIIJIJIIIIIJJIJJJIIIJJIIJJIJJJJJJJIJIIJIJJJIJIIJJJIIIIIJ) 
	input(colored(JIIJJJJJIIIJJJIIJJJJJIIIJJJJIIIIIIJIIJIIJJJJIIIJJIIJJIIJJJIIIJJIIJJJIIIJJII, JIIJJJIJJIIIJJIJIIJIJIIIIIJJIJJJIIIJJIIJJIJJJJJJJIJIIJIJJIJJIJIIJJJIIIIIJ))