JIJJJJJIIIIJJJIIJJIIJJIIIJJJIIJJJJIIJJJJJIIJJIIIIJJIIIJJJII = "====== Fake Ip Address ======"
JIJJJJJIIIIJJJIIJJIIJJIIJJJJIIJIJIIJJJJJIIJJIIIIJJIIIJJJII = "red"
JIJJJJJIIIIJJJIIJJIIJJIIJJJJIIJJJJIIJJJJJIIJJIIIIJJIIIJJJII = "[ This Tool Generates random ipv4 & ipv6 not changing it ! ]"
JIJJJJJIIIIJJJIIJJIIJJIIJJJJIIJJJJIJJJJJIIJJIIIIJJIIIJJJII = "ipv4:"
JIJJJJJIIJJJIIJJIIJJIIJJJJIIJJJJIJJJJJJIIJJJIIIIJJIIIJJJII = "ipv6:"
JIJJJJJIIIIJJJIIJJIIJJIIJJJJIIJIJIIJJJJJIIJJJIJIIIJJJIIIJJJII = "Press Enter to exit ..."

def JIJJJJJIIIIJJJIIJJIIJJIIJJIJIIJIIJIIJJIJ():
    from faker import Faker
    from termcolor import colored
    JIJJJJJIIIIJJJIIJJIIJJIIJJJJIIJIJIIJJIIIJIJJJIIIJIIIJJJIIIJJJIIIJJIIJI = Faker()
    print(JIJJJJJIIIIJJJIIJJIIJJIIJJJJIIJJJJIIJJJJJIIJJIIIIJJIIIJJJII)
    print(JIJJJJJIIIIJJJIIJJIIJJIIIJJJIIJJJJIIJJJJJIIJJIIIIJJIIIJJJII)
    print(colored(JIJJJJJIIIIJJJIIJJIIJJIIJJJJIIJJJJIJJJJJIIJJIIIIJJIIIJJJII, JIJJJJJIIIIJJJIIJJIIJJIIJJJJIIJIJIIJJJJJIIJJIIIIJJIIIJJJII),JIJJJJJIIIIJJJIIJJIIJJIIJJJJIIJIJIIJJIIIJIJJJIIIJIIIJJJIIIJJJIIIJJIIJI.ipv4()) 
    print(colored(JIJJJJJIIJJJIIJJIIJJIIJJJJIIJJJJIJJJJJJIIJJJIIIIJJIIIJJJII, JIJJJJJIIIIJJJIIJJIIJJIIJJJJIIJIJIIJJJJJIIJJIIIIJJIIIJJJII),JIJJJJJIIIIJJJIIJJIIJJIIJJJJIIJIJIIJJIIIJIJJJIIIJIIIJJJIIIJJJIIIJJIIJI.ipv6())
    input(colored(JIJJJJJIIIIJJJIIJJIIJJIIJJJJIIJIJIIJJJJJIIJJJIJIIIJJJIIIJJJII, JIJJJJJIIIIJJJIIJJIIJJIIJJJJIIJIJIIJJJJJIIJJIIIIJJIIIJJJII))
    
def JIJJJJJIIIIJJJIIJJIIJJIJJIJIJIJIIJIIJJIJ():
    from faker import Faker
    from termcolor import colored
    JIJJJJJIIIIJJJIIJJIIJJIIJJJJIIJIJIIJJIIIJIJJJIIIJIIIJJJIIIJJJIIIJJIIJI = Faker()
    print(JIJJJJJIIIIJJJIIJJIIJJIIJJJJIIJJJJIIJJJJJIIJJIIIIJJIIIJJJII)
    print(JIJJJJJIIIIJJJIIJJIIJJIIIJJJIIJJJJIIJJJJJIIJJIIIIJJIIIJJJII)
    print(colored(JIJJJJJIIIIJJJIIJJIIJJIIJJJJIIJJJJIJJJJJIIJJIIIIJJIIIJJJII, JIJJJJJIIIIJJJIIJJIIJJIIJJJJIIJIJIIJJJJJIIJJIIIIJJIIIJJJII),JIJJJJJIIIIJJJIIJJIIJJIIJJJJIIJIJIIJJIIIJIJJJIIIJIIIJJJIIIJJJIIIJJIIJI.ipv4()) 
    print(colored(JIJJJJJIIJJJIIJJIIJJIIJJJJIIJJJJIJJJJJJIIJJJIIIIJJIIIJJJII, JIJJJJJIIIIJJJIIJJIIJJIIJJJJIIJIJIIJJJJJIIJJIIIIJJIIIJJJII),JIJJJJJIIIIJJJIIJJIIJJIIJJJJIIJIJIIJJIIIJIJJJIIIJIIIJJJIIIJJJIIIJJIIJI.ipv6())
    input(colored(JIJJJJJIIIIJJJIIJJIIJJIIJJJJIIJIJIIJJJJJIIJJJIJIIIJJJIIIJJJII, JIJJJJJIIIIJJJIIJJIIJJIIJJJJIIJIJIIJJJJJIIJJIIIIJJIIIJJJII))
    
def JIJJJJJIIIIJJJIIJJIIJJIIJJIJIJIJIIJIIJJIJ():
    from faker import Faker
    from termcolor import colored
    JIJJJJJIIIIJJJIIJJIIJJIIJJJJIIJIJIIJJIIIJIJJJIIIJIIIJJJIIIJJJIIIJJIIJI = Faker()
    print(JIJJJJJIIIIJJJIIJJIIJJIIJJJJIIJJJJIIJJJJJIIJJIIIIJJIIIJJJII)
    print(JIJJJJJIIIIJJJIIJJIIJJIIIJJJIIJJJJIIJJJJJIIJJIIIIJJIIIJJJII)
    print(colored(JIJJJJJIIIIJJJIIJJIIJJIIJJJJIIJJJJIJJJJJIIJJIIIIJJIIIJJJII, JIJJJJJIIIIJJJIIJJIIJJIIJJJJIIJIJIIJJJJJIIJJIIIIJJIIIJJJII),JIJJJJJIIIIJJJIIJJIIJJIIJJJJIIJIJIIJJIIIJIJJJIIIJIIIJJJIIIJJJIIIJJIIJI.ipv4()) 
    print(colored(JIJJJJJIIJJJIIJJIIJJIIJJJJIIJJJJIJJJJJJIIJJJIIIIJJIIIJJJII, JIJJJJJIIIIJJJIIJJIIJJIIJJJJIIJIJIIJJJJJIIJJIIIIJJIIIJJJII),JIJJJJJIIIIJJJIIJJIIJJIIJJJJIIJIJIIJJIIIJIJJJIIIJIIIJJJIIIJJJIIIJJIIJI.ipv6())
    input(colored(JIJJJJJIIIIJJJIIJJIIJJIIJJJJIIJIJIIJJJJJIIJJJIJIIIJJJIIIJJJII, JIJJJJJIIIIJJJIIJJIIJJIIJJJJIIJIJIIJJJJJIIJJIIIIJJIIIJJJII))
    
def JIJJJJJIIIIJJJIIJJIIJJIIJIJIJIJIJIIJJIJ():
    from faker import Faker
    from termcolor import colored
    JIJJJJJIIIIJJJIIJJIIJJIIJJJJIIJIJIIJJIIIJIJJJIIIJIIIJJJIIIJJJIIIJJIIJI = Faker()
    print(JIJJJJJIIIIJJJIIJJIIJJIIJJJJIIJJJJIIJJJJJIIJJIIIIJJIIIJJJII)
    print(JIJJJJJIIIIJJJIIJJIIJJIIIJJJIIJJJJIIJJJJJIIJJIIIIJJIIIJJJII)
    print(colored(JIJJJJJIIIIJJJIIJJIIJJIIJJJJIIJJJJIJJJJJIIJJIIIIJJIIIJJJII, JIJJJJJIIIIJJJIIJJIIJJIIJJJJIIJIJIIJJJJJIIJJIIIIJJIIIJJJII),JIJJJJJIIIIJJJIIJJIIJJIIJJJJIIJIJIIJJIIIJIJJJIIIJIIIJJJIIIJJJIIIJJIIJI.ipv4()) 
    print(colored(JIJJJJJIIJJJIIJJIIJJIIJJJJIIJJJJIJJJJJJIIJJJIIIIJJIIIJJJII, JIJJJJJIIIIJJJIIJJIIJJIIJJJJIIJIJIIJJJJJIIJJIIIIJJIIIJJJII),JIJJJJJIIIIJJJIIJJIIJJIIJJJJIIJIJIIJJIIIJIJJJIIIJIIIJJJIIIJJJIIIJJIIJI.ipv6())
    input(colored(JIJJJJJIIIIJJJIIJJIIJJIIJJJJIIJIJIIJJJJJIIJJJIJIIIJJJIIIJJJII, JIJJJJJIIIIJJJIIJJIIJJIIJJJJIIJIJIIJJJJJIIJJIIIIJJIIIJJJII))
    
def JIJJJJIIIJJJIIJJIIJJIIJJIJIJIJIIJIIJJIJ():
    from faker import Faker
    from termcolor import colored
    JIJJJJJIIIIJJJIIJJIIJJIIJJJJIIJIJIIJJIIIJIJJJIIIJIIIJJJIIIJJJIIIJJIIJI = Faker()
    print(JIJJJJJIIIIJJJIIJJIIJJIIJJJJIIJJJJIIJJJJJIIJJIIIIJJIIIJJJII)
    print(JIJJJJJIIIIJJJIIJJIIJJIIIJJJIIJJJJIIJJJJJIIJJIIIIJJIIIJJJII)
    print(colored(JIJJJJJIIIIJJJIIJJIIJJIIJJJJIIJJJJIJJJJJIIJJIIIIJJIIIJJJII, JIJJJJJIIIIJJJIIJJIIJJIIJJJJIIJIJIIJJJJJIIJJIIIIJJIIIJJJII),JIJJJJJIIIIJJJIIJJIIJJIIJJJJIIJIJIIJJIIIJIJJJIIIJIIIJJJIIIJJJIIIJJIIJI.ipv4()) 
    print(colored(JIJJJJJIIJJJIIJJIIJJIIJJJJIIJJJJIJJJJJJIIJJJIIIIJJIIIJJJII, JIJJJJJIIIIJJJIIJJIIJJIIJJJJIIJIJIIJJJJJIIJJIIIIJJIIIJJJII),JIJJJJJIIIIJJJIIJJIIJJIIJJJJIIJIJIIJJIIIJIJJJIIIJIIIJJJIIIJJJIIIJJIIJI.ipv6())
    input(colored(JIJJJJJIIIIJJJIIJJIIJJIIJJJJIIJIJIIJJJJJIIJJJIJIIIJJJIIIJJJII, JIJJJJJIIIIJJJIIJJIIJJIIJJJJIIJIJIIJJJJJIIJJIIIIJJIIIJJJII))